# Generated by Django 4.1.5 on 2023-01-30 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_membersession_expire_time_membersession_iat_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accountbook',
            },
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='membersession',
            name='id',
        ),
        migrations.AlterField(
            model_name='membersession',
            name='session_id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AccountBookHistory',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=1)),
                ('memo', models.CharField(max_length=128)),
                ('amount', models.PositiveIntegerField()),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('account_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='application.accountbook')),
            ],
            options={
                'db_table': 'accountbook_history',
            },
        ),
        migrations.AddField(
            model_name='accountbook',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
